version: "3"
services:

  ## Database (Postgres)
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test1234
      POSTGRES_MULTIPLE_DATABASES: "lg_template_dev,lg_template_test"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      
  ## PGAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: test1234
    ports:
      - "4040:80"
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

  ## Slack Agent
  # slack_agent:
  #   container_name: slack_agent
  #   image: ryaneggz/slack-agent:latest
  #   env_file: .env.slack
  #   network_mode: host
  #   restart: always

  # Graphchat
  # graphchat:
  #   image: ryaneggz/graphchat:0.0.1-rc65
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    # container_name: graphchat
    # env_file:
    #   - ./backend/.env
    # ports:
    #   - "8005:8000"
    # depends_on:
    #   - postgres

  # Ollama (AI Servic
#   ollama:
#     image: ollama/ollama
#     container_name: ollama
#     runtime: nvidia
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               capabilities: [gpu]
#     volumes:
#       - ollama:/root/.ollama
#     ports:
#       - "11434:11434"
#     command: >
#       sh -c "
#         ollama pull llama3.2-vision &&
#         tail -f /dev/null
#       "
# volumes:
#   ollama: