name: services

networks:
    services:
        name: services

services:
    search_engine:
        image: searxng/searxng
        ports:
            - "8080:8080"
        volumes:
            - ./docker/searxng/settings.yml:/etc/searxng/settings.yml:ro
        environment:
            SEARXNG_SETTINGS_PATH: /etc/searxng/settings.yml
        networks:
            - services
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 1G

    dozzle:
        image: amir20/dozzle:latest
        ports:
            - "8088:8080"
        environment:
            DOZZLE_NO_ANALYTICS: "true"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - services
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: 256M
