version: "3"
services:

  # Database (Postgres)
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test1234
      POSTGRES_MULTIPLE_DATABASES: "lg_template_dev,lg_template_test"
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      
  # PGAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: test1234
    ports:
      - "4040:80"
    networks:
      - app-network
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

  # Graphchat
  graphchat:
    # image: ryaneggz/graphchat:b572a97
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphchat
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres

  slack-response:
    container_name: slack_response
    image: ryaneggz/slack-agent:latest
    env_file: .env.slack
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - graphchat

# Add networks section at the bottom of the file
networks:
  app-network:
    driver: bridge

# ubuntu24:
#   image: ubuntu:24.04
#   container_name: ubuntu24
#   command: tail -f /dev/null