site_name: Enso Cloud ☁️
site_dir: src/public/docs
docs_dir: ../docs
use_directory_urls: false
nav:
  - Home: /docs/
  # - Agents:
  #   - Overview: agents/index.md
  #   - API: /api#/Agent
  # - Settings:
  #   - Overview: settings/index.md
  #   - API: /api#/Settings
  # - Storage:
  #   - Overview: storage/index.md
  #   - API: /api#/Storage
  # - Threads:
  #   - Overview: threads/index.md
  #   - API: /api#/Thread
  - Tools:
    - Overview: tools/tools.md
    - Search: tools/search.md
    - Shell: tools/shell_exec.md
    - MCP: tools/mcp.md
    # - A2A: tools/a2a.md
    
  - API: /api
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - mkdocstrings
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
extra:
  base_url: '/docs/'
  homepage: /
