site_name: Thread Agent
site_url: http://localhost:8000/docs/
site_dir: src/public/docs
docs_dir: ../docs
use_directory_urls: false
nav:
  - Home: /docs/
  - Deploy:
    - DigitalOcean: deploy/digitalocean.md
    # - Docker: deploy/docker.md
    # - Kubernetes: deploy/kubernetes.md
    # - AWS: deploy/aws.md
    - AWS RDS: deploy/aws-rds.md
  - Tools:
    - Shell Local: tools/shell_local.md
    - Shell Docker: tools/shell_docker.md
  - API: /api
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - mkdocstrings
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
extra:
  base_url: '/docs/'
  homepage: /
