# ./docker/searxng/settings.yml
use_default_settings: true # <- rely on built-in defaults
server:
    bind_address: 0.0.0.0
    port: 8888
    api: true # enable API
    secret_key: "super-secret-key"
search:
    formats: # allow JSON API responses
        - html
        - json
    default_lang: en # default language for search results
