steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Cache Python dependencies
    id: cache-python
    uses: actions/cache@v4
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
      restore-keys: |
          ${{ runner.os }}-pip-

  - name: Install dependencies
    working-directory: ./backend
    run: |
      env | sort
      pip install --upgrade pip
      pip install uv
      uv sync --frozen --no-cache --no-dev

  - name: Build docs
    run: |
      # Copy docs folder to backend directory
      cp -r docs backend/docs
      
      # Change to backend directory
      cd backend
      
      # Build docs
      # mkdocs build --site-dir src/public/docs
      
      # Cleanup docs folder from backend
      rm -rf docs || true

  - name: Save Python dependencies cache
    if: steps.cache-python.outputs.cache-hit != 'true'
    id: save-cache-python
    uses: actions/cache@v4
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}