name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      DOCKER_USERNAME: ryaneggz
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        working-directory: ./backend
        run: |
          # Use the tag name for the Docker image version
          DOCKER_IMAGE=ryaneggz/graphchat:${GITHUB_REF#refs/tags/}
          DOCKER_LATEST=ryaneggz/graphchat:latest
          
          echo "Building images: $DOCKER_IMAGE and $DOCKER_LATEST"
          docker build --squash -t $DOCKER_IMAGE -t $DOCKER_LATEST .
          docker push $DOCKER_IMAGE
          docker push $DOCKER_LATEST
