name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Frontend
        uses: ./.github/workflows/steps/frontend-install.yml

      - name: Prune Frontend
        working-directory: ./frontend
        run: npm prune --production

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Build Backend
        uses: ./.github/workflows/steps/backend-build.yml

      - name: Docker Build
        uses: ./.github/workflows/steps/docker-build.yml
