name: Deploy

on:
  push:
    tags:
      - '*rc*'

jobs:
  ###############################################################
  ## Deploy to VM
  ###############################################################
  deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'rc') }}
    environment: Dev
    steps:
    - name: Deploy to VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
        # Add host to known hosts
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        
        # Extract tag from ref
        TAG=${GITHUB_REF#refs/tags/}
        
        
        # SSH into server and deploy
        ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "
          set -e  # Exit immediately if a command fails
          
          echo 'User: $(whoami)'
          echo 'Hostname: $(hostname)'
          echo 'OS: $(uname -a)'
          echo 'Uptime: $(uptime -p)'
          docker ps
          tmux ls || true  # Won't fail if no sessions exist
          
          cd ~/agent_api
          git fetch --all --tags
          git checkout ${TAG} -f  # Force checkout the tag
          
          # Kill any existing agent_api tmux sessions
          echo 'Checking for existing agent_api sessions...'
          tmux ls 2>/dev/null | grep '^agent_api' | cut -d: -f1 | xargs -I{} tmux kill-session -t {} || echo 'No existing agent_api sessions found'
          
          # Create new tmux session with version in name
          SESSION_NAME=\"agent_api_${TAG}\"
          tmux new-session -d -s \"\${SESSION_NAME}\" '
            cd ~/agent_api/backend
            source .venv/bin/activate
            uv pip install -r requirements.txt
            export APP_VERSION=${TAG}
            export APP_USERNAME=aiuser
            export APP_PORTAL_ENABLED=1
            export APP_PASSWORD=${{ secrets.APP_PASSWORD }}
            export ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
            export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            export POSTGRES_CONNECTION_STRING=${{ secrets.POSTGRES_CONNECTION_STRING }}
            export POSTGRES_CONNECTION_STRING_SANDBOX=${{ secrets.POSTGRES_CONNECTION_STRING_SANDBOX }}
            python main.py
          '
          
          echo \"Deployment completed successfully with session: \${SESSION_NAME}\"
        "
